services:
  - type: web
    name: ccl-digital-visitor
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        value: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
